### ISSUE TITLE
Removing cover image

### ISSUE THREAD

**Issue by RuABraun** [zivong/jekyll-theme-hydure#2]
Hi, thanks for making this.

How can I remove the cover image and get back the default look? (like here https://hyde.getpoole.com/)

**Comment by zivong** [comment]
The cover image is non-removable, but maybe I should provide an option to set up a cover with only pure color in the next version.

**Comment by RuABraun** [comment]
Thanks for the reply!

I figured out how to do it. For anyone else:

Inside `_layouts/default.html` I set the sidebar div line to:
`<div class="sidebar pure-u-1 pure-u-md-1-4" style="background-color: #202421">`

**Comment by RuABraun** [comment]
Side question when I try and setup `_data/social.yml` I get an error: `mapping values are not allowed in this context` ? Seems to be about the `:` symbol?

**Comment by RuABraun** [comment]
A question :) @zivong 

How can I get the header in the sidebar to be aligned to the top rather than the bottom?

**Comment by zivong** [comment]
> How can I get the header in the sidebar to be aligned to the top rather than the bottom?

Replace the below line with `top: 0;`.

https://github.com/zivong/jekyll-theme-hydure/blob/01db81c9c4df462cba5a08461a0ec70485dcba3b/_sass/hydure/_sidebar.scss#L74
