### ISSUE TITLE
[FR] Add authors section and archive by author

### ISSUE THREAD

**Issue by chepo92** [zivong/jekyll-theme-hydure#3]
Hi, Thank you and nice template,
May it be possible to add authors section and archive by author?

**Comment by zivong** [comment]
Since one of the purposes of this theme is to keep it minimal, I think I won't add the archive by author in the future. But I think this feature is very easy to implement; it's similar to the archive by category. So just leave this to motivated users. 😀

**Comment by chepo92** [comment]
Already implemented it, I understand you want to keep it minimal, but you may want to add an "extended" branch for those additional features and community contributions, IMHO.
